/**
 * Enum de retornos padronizados para o BFF
 * Mantém consistência nas respostas de erro
 */
export enum MappedsReturnsEnum {
  // Erros de Autenticação (401)
  NAO_AUTENTICADO = 'NAO_AUTENTICADO',
  TOKEN_INVALIDO = 'TOKEN_INVALIDO',
  TOKEN_EXPIRADO = 'TOKEN_EXPIRADO',

  // Erros de Autorização (403)
  SEM_PERMISSAO = 'SEM_PERMISSAO',
  ACESSO_NEGADO = 'ACESSO_NEGADO',

  // Erros de Validação (400)
  DADOS_INVALIDOS = 'DADOS_INVALIDOS',
  PARAMETRO_OBRIGATORIO = 'PARAMETRO_OBRIGATORIO',
  FORMATO_INVALIDO = 'FORMATO_INVALIDO',

  // Erros de Negócio (404)
  DADOS_NAO_ENCONTRADOS = 'DADOS_NAO_ENCONTRADOS',
  RECURSO_NAO_ENCONTRADO = 'RECURSO_NAO_ENCONTRADO',

  // Erros de Integração (502, 503, 504)
  ERRO_INTEGRACAO = 'ERRO_INTEGRACAO',
  SERVICO_INDISPONIVEL = 'SERVICO_INDISPONIVEL',
  TIMEOUT_INTEGRACAO = 'TIMEOUT_INTEGRACAO',
  ERRO_API_EXTERNA = 'ERRO_API_EXTERNA',

  // Erros de Sistema (500)
  ERRO_INTERNO = 'ERRO_INTERNO',
  ERRO_INESPERADO = 'ERRO_INESPERADO',

  // Rate Limiting (429)
  MUITAS_REQUISICOES = 'MUITAS_REQUISICOES',
}
